# Generated by Django 4.2.2 on 2023-06-08 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('betopoem', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poem',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
