# Generated by Django 4.2.2 on 2023-06-08 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('betopoem', '0002_alter_poem_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='poem',
            name='similars',
            field=models.ManyToManyField(blank=True, to='betopoem.poem'),
        ),
    ]
