# Generated by Django 4.2.2 on 2023-07-30 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("betopoem", "0004_poem_detail_url"),
    ]

    operations = [
        migrations.CreateModel(
            name="PoemSubCorpus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField(max_length=200, unique=True)),
                ("title", models.CharField(max_length=200, null=True)),
                ("author", models.CharField(max_length=200, null=True)),
                ("content", models.TextField(blank=True, null=True)),
                ("tfidf", models.TextField(blank=True, max_length=200, null=True)),
                ("detail_url", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "similars",
                    models.ManyToManyField(blank=True, to="betopoem.poemsubcorpus"),
                ),
            ],
            options={
                "ordering": ["-title"],
            },
        ),
    ]
