# Generated by Django 4.2.2 on 2023-08-01 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("betopoem", "0005_poemsubcorpus"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="poemsubcorpus",
            name="tfidf",
        ),
        migrations.AddField(
            model_name="poemsubcorpus",
            name="keywords",
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
