# Generated by Django 4.2.2 on 2023-08-01 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("betopoem", "0006_remove_poemsubcorpus_tfidf_poemsubcorpus_keywords"),
    ]

    operations = [
        migrations.AlterField(
            model_name="poemsubcorpus",
            name="keywords",
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
